[project]
name = "bollard-detect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nial", email = "48334675+nmcc1212@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
bollard-detect = "bollard_detect:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
